name: 'Preflight Checklist'
description: 'Checks things before they are deployed'
inputs:
  token:
    description: 'GitHub token'
    required: true
  target-aws-key-id:
    description: 'The target aws access key id'
    required: true
  target-aws-secret-access-key:
    description:  'The target aws secret access key'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
